GET http://localhost:5501/users

###
POST http://localhost:5501/users
Content-Type: application/json

{
    "name": "Maira",
    "password" : "password"
}

###
POST http://localhost:5501/users/login
Content-Type: application/json

{
    "name": "Maira",
    "password" : "password"
}

